apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-components
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
          - name: argo-istio
            namespace: argocd
          - name: mysqld-exporter
          - name: cert-manager
          - name: yopass

  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/raynix/argo-gitops.git
        targetRevision: HEAD
        path: "{{.name}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.name}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      destination:
      {{- if (hasKey . "namespace")}}
        namespace: {{ .namespace}}
      {{- end}}
