apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-components
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
          - name: argo-istio
            namespace: argocd
          - name: bayleaves
            path: .
            repoURL: https://github.com/raynix/bay-leaves.git
          - name: mysqld-exporter
          - name: cert-manager
          - name: yopass

  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      source:
        targetRevision: HEAD
        path: "{{.name}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        path: {{ if (hasKey . "path")}}{{.path}}{{else}}{{.name}}{{end}}
        repoURL: {{ if (hasKey . "repoURL")}}{{.repoURL}}{{else}}https://github.com/raynix/argo-gitops.git{{end}}
      destination:
        namespace: {{ if (hasKey . "namespace")}}{{.namespace}}{{else}}{{.name}}{{end}}
