apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: bay-leaves
            path: .
            repoURL: https://github.com/raynix/bay-leaves.git
          - name: bluesky
          - name: rusty-sonar
            path: .kustomize/raynix
            repoURL: https://github.com/raynix/rusty-sonar.git
          - name: saus-prod
            path: .kustomize/sausl.ink
            repoURL: https://github.com/raynix/saus.git
          - name: yopass

  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default
      source:
        targetRevision: HEAD
        path: "{{.name}}"
        repoURL: https://github.com/raynix/argo-gitops.git
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        path: {{ if (hasKey . "path")}}{{.path}}{{else}}{{.name}}{{end}}
        {{- if (hasKey . "repoURL")}}
        repoURL: {{.repoURL}}
        {{- end}}
      destination:
        namespace: {{ if (hasKey . "namespace")}}{{.namespace}}{{else}}{{.name}}{{end}}
