apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-components
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/raynix/argo-gitops.git
        revision: HEAD
        directories:
          - path: mysqld-exporter
          - path: cert-manager
          - path: yopass
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/raynix/argo-gitops.git
        targetRevision: HEAD
        path: "{{.path.basename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
