apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress-sites
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/raynix/kubepress.git
        revision: HEAD
        directories:
          - path: tanka/environments/*
          - path: tanka/environments/raynix
            exclude: true
  template:
    metadata:
      name: "wordpress-{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/raynix/kubepress.git
        targetRevision: HEAD
        path: "{{index .path.segments 0}}"
        plugin:
          env:
            - name: TK_ENV
              value: "{{.path.basename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "wordpress-{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
