apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress-sites
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: dote
          - name: raynix

  template:
    metadata:
      name: "wordpress-{{.name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/raynix/kubepress.git
        targetRevision: HEAD
        path: tanka
        plugin:
          env:
            - name: TK_ENV
              value: "{{.name}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "wordpress-{{.name}}"
      syncPolicy:
        automated:
          prune: true
