apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-backup
  labels:
    app: cronjob-backup
spec:
  schedule: 0 16 * * 0
  jobTemplate:
    spec:
      template:
        metadata:
          name: cronjob-backup
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
          securityContext:
            fsGroup: 991
            runAsGroup: 991
            runAsUser: 991
          restartPolicy: Never
          volumes:
            - name: gcp-sa
              secret:
                secretName: backup-gcp-sa
          containers:
            - name: backup-tool
              image: ghcr.io/raynix/backup:v0.38
              command:
                - /bin/bash
                - -c
                - |
                  /mastodon.sh $(DOMAIN) /gcp/${SERVICE_ACCOUNT_KEY} ${BACKUP_BUCKET}
              envFrom:
                - secretRef:
                    name: mastodon
                - secretRef:
                    name: backup-gcp-env
              volumeMounts:
                - name: gcp-sa
                  mountPath: /gcp
