apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - conf.yaml

resources:
  - redis.yaml
  - pvc.yaml
  - web-deploy.yaml
  - sidekiq-deploy.yaml
  - streaming-deploy.yaml
  - job-db-migration.yaml
  - gateway.yaml
  - virtual-service.yaml
  - cronjob-media-remove-orphans.yaml
  - cronjob-backup.yaml
  - http-route.yaml

vars:
  - name: DOMAIN
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: mastodon-web
    fieldref:
      fieldpath: metadata.annotations.domain
  - name: CERT
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: mastodon-web
    fieldref:
      fieldpath: metadata.annotations.cert
