---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: awes-one
  namespace: istio-system
spec:
  secretName: awes-one-cert
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - raynix.info
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - awes.one
    - argo.awes.one
    - feedi.awes.one
    - grafana.awes.one
    - httpbin.awes.one
    - luckybirdie.awes.one
    - wordsquad.awes.one
    - yopass.awes.one
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
