apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy
  name: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - image: ubuntu:noble
          imagePullPolicy: IfNotPresent
          name: ubuntu
          command:
            - sleep
            - infinity
