apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-tests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: dummy-a
                - name: dummy-b
          - list:
              elements:
                - project: alpha
                - project: beta

  template:
    metadata:
      name: "{{.name}}-in-{{.project}}"
    spec:
      project: "{{.project}}"
      source:
        targetRevision: HEAD
        path: dummy
        repoURL: https://github.com/raynix/argo-gitops.git
        kustomize:
          patches:
            - target:
                kind: Deployment
                name: dummy
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{.name}}-{{.project}}
      destination:
        namespace: "dummy-{{.project}}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
