{
 "title": "My K8s Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "New",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node No.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=\"/\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta( kube_pod_container_status_restarts_total[15m]))"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_network_receive_bytes_total[5m]))"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_network_transmit_bytes_total[5m]))"
    }
   ]
  },
  {
   "title": "Old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Restarts/Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[5m])",
     "legendFormat": "restarted: {{ namespace }} - {{ pod }}"
    },
    {
     "expr": "increase(kube_pod_status_phase{phase=\"Pending\"}[5m])",
     "legendFormat": "pending: {{ namespace }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Ingress Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (destination_service) (increase(istio_requests_total[5m]))",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  {
   "title": "Proxy Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(node_network_receive_bytes_total{job=~\"host_proxy.*\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proxy Free CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (avg(irate(node_cpu_seconds_total{job=~'host_proxy.*', mode=\"idle\"}[5m])) by (job))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Master Free CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (node) (irate(node_cpu_seconds_total{node=\"kmaster2\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Master Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{node=\"kmaster2\"})",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Master Free Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_filesystem_free_bytes{node=\"kmaster2\"})",
     "legendFormat": "free space"
    }
   ]
  },
  {
   "title": "Nodes Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (irate (container_network_receive_bytes_total[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes Free CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (node) (irate(node_cpu_seconds_total{node=~\"knode.+\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Nodes Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (node) (node_memory_MemAvailable_bytes{node=~\"knode.+\"})",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Nodes Free Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (node) (node_filesystem_free_bytes{node=~\"knode.+\"})",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Nodes Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (irate (container_network_transmit_bytes_total[5m])) by (kubernetes_io_hostname)",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}