{
 "title": "Machines At Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Hostname", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Running Processes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_procs_running{job=\"host_$Hostname\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "User",
     "expr": "avg by (job) (irate(node_cpu_seconds_total{job=\"host_$Hostname\", mode=\"idle\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- increase(node_network_receive_bytes_total{job=\"host_$Hostname\"}[5m])",
     "legendFormat": "{{device}} RX"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{job=\"host_$Hostname\"}[5m])",
     "legendFormat": "{{device}} TX"
    }
   ]
  },
  {
   "title": "System Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"host_$Hostname\"}",
     "legendFormat": "{{chip}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "Memory In Use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"host_$Hostname\"} - node_memory_MemAvailable_bytes{job=\"host_$Hostname\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{job=\"host_$Hostname\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(node_disk_io_time_weighted_seconds_total{job=\"host_$Hostname\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk - Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_path",
     "expr": "node_filesystem_free_bytes{job=\"host_$Hostname\", device=~\"/dev/(sd|nvm|mmc).*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  }
 ]
}