apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - config.yaml

resources:
  - ns.yaml
  - pv.yaml
  - pvc.yaml
  - virtual-service.yaml
  - http-route.yaml
  - helm-charts.yaml

configMapGenerator:
  - name: datasources
    namespace: grafana
    options:
      labels:
        grafana_datasource: "yes"
    files:
      - datasources.json
  - name: dashboards
    namespace: grafana
    options:
      labels:
        grafana_dashboard: "yes"
    files:
      - dashboard-test.json
      - dashboard-k8s.json
      - dashboard-machines.json
