apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: awes-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*.awes.one"
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: awes-one-cert
    - hosts:
        - "*.awes.one"
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubernetes-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: awes-https
      protocol: HTTPS
      port: 443
      hostname: "*.awes.one"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: awes-one-cert
    - name: awes-http
      protocol: HTTP
      port: 80
      hostname: "*.awes.one"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All

    - name: dote-https
      protocol: HTTPS
      port: 443
      hostname: "dote.blog"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: wordpress-dote
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: wordpress-dote-cert
    - name: dote-http
      protocol: HTTP
      port: 80
      hostname: "dote.blog"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: wordpress-dote

    - name: raynix-https
      protocol: HTTPS
      port: 443
      hostname: "raynix.info"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: wordpress-raynix
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: wordpress-raynix-cert
    - name: raynix-http
      protocol: HTTP
      port: 80
      hostname: "raynix.info"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: wordpress-dote
